FROM node:20-alpine AS development-dependencies-env
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
COPY . /app
WORKDIR /app
RUN pnpm install --frozen-lockfile

FROM node:20-alpine AS production-dependencies-env
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
COPY ./package.json pnpm-lock.yaml /app/
WORKDIR /app
RUN pnpm install --frozen-lockfile

FROM node:20-alpine AS build-env
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
COPY . /app/
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
RUN pnpm build

FROM node:20-alpine
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate
COPY ./package.json pnpm-lock.yaml /app/
COPY --from=production-dependencies-env /app/node_modules /app/node_modules
COPY --from=build-env /app/build /app/build
COPY drizzle.config.ts /app/
COPY drizzle /app/drizzle
WORKDIR /app
CMD ["sh", "-c", "pnpm db:push && pnpm start"]